name: Prepare New Release

on:
  push:
    branches:
      - main


jobs:
  GUT:
    runs-on: ubuntu-latest
    name: Unit & Integration Tests
    steps:
    - name: "‚úîÔ∏è Checkout"
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Check out personal godot-tester repository
      uses: actions/checkout@v3
      with:
        repository: db0/godot-tester
        path: ./.github/actions/godot-tester
      # Runs a single command using the runners shell
    - name: ‚öô Run Tests
      uses: ./.github/actions/godot-tester
      with:
        version: 3.4.4
        # should be long enough for asset import files to get generated
        import-time: 300
        assert-check: true
        # Allowing some fails on push, as sometimes randomly some asserts might false negative and I haven't yet located the precice reason for this inconsistency
        max-fails: 0
        # How long the test should be run before it's timed out and fails
        test-timeout: 3600
        # Directory containing Gut tests
        direct-scene: tests/cli/tests.tscn
  version_and_release:
    runs-on: ubuntu-latest
    name: Export Game
    needs: ["GUT"]
    steps:
    - name: "‚úîÔ∏è Checkout"
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: "ü§ñ Export game"
      uses: firebelley/godot-export@v3.0.0
      with:
        godot_executable_download_url: https://downloads.tuxfamily.org/godotengine/3.4/Godot_v3.4-stable_linux_headless.64.zip
        godot_export_templates_download_url: https://downloads.tuxfamily.org/godotengine/3.4/Godot_v3.4-stable_export_templates.tpz
        relative_project_path: ./
        base_version: Demo
        create_release: false
        archive_export_output: true
    - name: "üõ† Prepare files for publishing"
      shell: bash
      run: |
          cp -v /home/runner/.local/share/godot/dist/* .
    - name: "üöÄ Upload HTML5 version to itch.io"
      uses: josephbmanley/butler-publish-itchio-action@master
      env:
        BUTLER_CREDENTIALS: "${{ secrets.BUTLER_CREDENTIALS }}"
        CHANNEL: HTML5
        ITCH_GAME: card-game-framework
        ITCH_USER: dbzer0
        PACKAGE: HTML5.zip
        VERSION: Demo
